-- DO NOT EDIT THIS FILE
return {
  {
    "Everblush/nvim",
    name = "everblush",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("everblush")
    end,
  },
}